export const eventsData = [
  {
      id: 0,
      title: "Séance de Dédicace",
      description: "L'expert en controle de gestion M. Michel Yapithe lance officiellement les ventes de son ouvrage",
      date: "12 Mars 2026",
      time: "18:00 - 21:00",
      location: "Starland Hotel",
      participants: "120+ participants",
      image: "/event0.jpeg",
      category: "Dédicace",
      status: "À venir",
    },
    {
      id: 1,
      title: "Séance de Dédicace",
      description: "L'expert en controle de gestion M. Michel Yapithe lance officiellement les ventes de son ouvrage",
      date: "12 Février 2026",
      time: "18:30 - 21:00",
      location: "Immeuble Elite Office, Akwa",
      participants: "120+ participants",
      image: "/post4_0.jpeg",
      category: "Dédicace",
      status: "Terminé",
    },
    {
      id: 2,
      title: "Atelier Performance & KPI",
      description: "Formation pratique sur le pilotage de la performance et l'utilisation des indicateurs clés.",
      date: "05 Février 2026",
      time: "09:00 - 17:00",
      location: "Centre de formation, Douala",
      participants: "45 participants",
      image: "/event2.jpg",
      category: "Atelier",
      status: "Terminé",
    },    
  ];